--1. database exploration:

-- Retrieve a list of all tables in the database
select * from INFORMATION_SCHEMA.TABLES;
-- Retrieve all columns for a table
select * from INFORMATION_SCHEMA.COLUMNS ;
---------------------------------------------
--2.Dimensions Exploration

-- Retrieve a list of unique countries from which customers originate
SELECT DISTINCT country FROM gold.dim_customer ORDER BY country;
-- Retrieve a list of unique categories, subcategories, and products
SELECT DISTINCT category,subcategory,product_name FROM gold.dim_products
order by category,subcategory,product_name;
-----------------------------------------------------------
--3. Date Range Exploration 

-- Determine the first and last order date and the total duration in months
SELECT MIN(order_date) as first_order_date,
       MAX(order_date) as last_order_date,
	   DATEDIFF(YEAR,MIN(order_date), MAX(order_date)) as order_range_years
	   FROM gold.fact_sales

-- Find the youngest and oldest customer based on birthdate
SELECT MIN(birthdate) as oldest_birthdate,
	   DATEDIFF(YEAR,MIN(birthdate),GETDATE()) as oldest_date,
	   MAX(birthdate) as yongest_birthdate,
	   DATEDIFF(YEAR,MAX(birthdate),GETDATE()) as youngest_date
	   FROM gold.dim_customer
------------------------------------------------------------------
--4. Measures Exploration 

-- Generate a Report that shows all key metrics of the business
SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity' , SUM(quanity) FROM gold.fact_sales
UNION ALL
SELECT 'Average Price' , AVG(price) FROM gold.fact_sales
UNION ALL
SELECT 'Total Nr.Orders' , COUNT(DISTINCT order_number) FROM gold.fact_sales
UNION ALL
SELECT 'Total NR.Product' , count(product_number) FROM gold.dim_products
UNION ALL
SELECT 'Total NR.Customer' , COUNT(customer_key) FROM gold.dim_customer
---------------------------------------------------------------------
--5. Magnitude Analysis

--TOTAL CUS BY COUNTRIES
SELECT 
country,
COUNT(customer_key) as total_customers
FROM gold.dim_customer
GROUP BY country
ORDER BY total_customers DESC

--TOTAL CUS BY GENDER
SELECT 
gender,
COUNT(customer_key) as total_customers
FROM gold.dim_customer
GROUP BY gender
ORDER BY total_customers DESC

--TOTAL PRODUCT BY CATEGORY
SELECT
category,
COUNT(product_key)as total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

--AVG COST IN EACH CATEGORY
SELECT
category,
AVG(cost)as avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC

--TOTAL REVENUE GENERATED FROM EACH CATEGORY
SELECT 
P.category,
SUM(f.sales_amount) as total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key=f.product_key
GROUP BY P.category
ORDER BY total_revenue DESC

--TOTAL REVENUE GENERATED BY EACH CUSTOMER
SELECT 
C.customer_key,
C.first_name,
C.last_name,
SUM(f.sales_amount) as total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customer C
ON C.customer_key=f.customer_key
GROUP BY C.customer_key,
C.first_name,
C.last_name
ORDER BY total_revenue DESC

--DISTRIBUTION OF SOLD ITEMS ACROSS COUNTRIES
SELECT 
c.country,
SUM(f.quanity) as total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customer C
ON C.customer_key=f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC

SELECT *
FROM(
SELECT 
P.product_name,
SUM(f.sales_amount) as total_revenue,
ROW_NUMBER() OVER (ORDER BY SUM(f.sales_amount) DESC) AS rank_products
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key=f.product_key
GROUP BY P.product_name)t
WHERE rank_products <= 5
------------------------------------------
--6. Ranking Analysis

--which 5 product generate the highest revenue
SELECT TOP 5
P.product_name,
SUM(f.sales_amount) as total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key=f.product_key
GROUP BY P.product_name
ORDER BY total_revenue DESC

-- 5 WORST PERFORMING PRODUCTS IN TERMS OF SALES
SELECT TOP 5
P.product_name,
SUM(f.sales_amount) as total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key=f.product_key
GROUP BY P.product_name
ORDER BY total_revenue 

SELECT *
FROM(
SELECT 
P.product_name,
SUM(f.sales_amount) as total_revenue,
ROW_NUMBER() OVER (ORDER BY SUM(f.sales_amount) ) AS rank_products
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key=f.product_key
GROUP BY P.product_name)t
WHERE rank_products <= 5

--find top 10 cus who have generated the higest revenue
SELECT TOP 10 
C.customer_key,
C.first_name,
C.last_name,
SUM(f.sales_amount) as total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customer C
ON C.customer_key=f.customer_key
GROUP BY C.customer_key,
C.first_name,
C.last_name
ORDER BY total_revenue DESC

--3 CUS WITH FEWEST ORDER PLACED
SELECT top 3
C.customer_key,
C.first_name,
C.last_name,
COUNT(DISTINCT order_number) as total_orders
FROM gold.fact_sales f
LEFT JOIN gold.dim_customer C
ON C.customer_key=f.customer_key
GROUP BY C.customer_key,
C.first_name,
C.last_name
ORDER BY total_orders,customer_key
